# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            Fifteen Whiskey
tagline:          'the first of some.'
description:      'Fifteen Whiskey.'
url:              http://tmzanco.github.io/
baseurl:          'http://tmzanco.github.io/fifteenwhiskey'
paginate:         5
timezone:         America/New_York

author:
  name:           'Fifteen Whiskey'
  url:            http://www.fifteenwhiskey.com

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/tmzanco/fifteenwhiskey
